models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
import os
from django.core.validators import RegexValidator
from django.utils import timezone
from django.core.mail import send_mail
from django.core.exceptions import ValidationError


# Create your models here.
# def get_file_path(request,filename):
#     original_filename=filename
#     nowTime=datetime.datetime.now().strftime('%Y%m%d%H:%M:%S')
#     filename="%s%s" % (nowTime.original_filename)
#     return os.path.join('uploads/',filename)

class State(models.Model):
    name=models.CharField(max_length=45,unique=True)

    class Mete:
        verbose_name='State'
        verbose_name_plural='State'

    def __str__(self):
        return self.name
    
class City(models.Model):
    name=models.CharField(max_length=45,unique=True)
    state=models.ForeignKey(State,on_delete=models.CASCADE)

    class Meta:
        verbose_name='City'
        verbose_name_plural='City'
    
    def __str__(self):
        return self.name



class Inquiry(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,blank=True,null=True)
    fname=models.CharField(max_length=85)
    lname=models.CharField(max_length=85)
    email=models.EmailField()
    subject=models.CharField(max_length=200)
    message=models.TextField(max_length=200)
    date=models.DateTimeField(default=timezone.now)
    is_replied=models.BooleanField(default=False)

    class Meta:
        verbose_name='Inquiry'
        verbose_name_plural='Inquiry'
    
    def __str__(self):
        return f"Inquiry By - {self.fname} - {self.email}"

class InquiryReply(models.Model):
    inquiry=models.ForeignKey(Inquiry,on_delete=models.CASCADE,related_name="replies")
    message=models.TextField()
    sent_at=models.DateTimeField(default=timezone.now)

    class Meta:
        verbose_name='Response to Inquiry'
        verbose_name_plural='Response to Inquiry'

    def __str__(self):
        return f"Inquiry Reply - {self.inquiry.subject} - {self.sent_at}"

    def get_inquiry_email(self):
        return self.inquiry.email
    get_inquiry_email.short_description="Inquiry Email"

    def send_email(self):
        try:
            send_mail(
                subject='Reply to your inquiry',
                message=self.message,
                from_email='himanshidevani22@gmail.com',
                recipient_list=[self.inquiry.email],
                fail_silently=False
            )
        except Exception as e:
            print(f'An error occurred: {e}')

    def save(self,*args,**kwargs):
        if not self.pk:
            self.send_email()
            self.inquiry.is_replied=True
            self.inquiry.save()
        super().save(*args,**kwargs)


class profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE, related_name="profile")
    is_email_verified=models.BooleanField(default=False)
    email_token=models.CharField(max_length=100,null=True,blank=False)
    profile_image=models.ImageField(upload_to='profile')

    def get_cart_count(self):
        return CartItems.objects.filter(Cart.is_paid == False, Cart.user == self.user).count()

def get_file_path(instance,filename):
    return f"uploads/{filename}"

class Category(models.Model):
    category_slug = models.CharField(max_length=150,null=False,blank=False)
    c_name=models.CharField(max_length=20,null=False,blank=False)
    description=models.TextField(max_length=500,null=False,blank=False)
    status=models.BooleanField(default=False,help_text="0=default,1=Hidden")
    trending=models.BooleanField(default=False,help_text="0=default,1=Hidden")
    meta_title=models.CharField(max_length=150,null=False,blank=False)
    meta_keyword=models.CharField(max_length=150,null=False,blank=False)
    meta_description=models.TextField(max_length=500,null=False,blank=False)
    created_at=models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f"{self.c_name}"

class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    product_slug = models.CharField(max_length=150, null=False, blank=False)
    p_name = models.CharField(max_length=50, null=False, blank=False, unique=True)
    p_image = models.ImageField(upload_to=get_file_path, null=True, blank=True)
    small_description = models.CharField(max_length=250, null=False, blank=False)
    quantity = models.IntegerField(null=False, blank=False)
    description = models.TextField(max_length=500, null=False, blank=False)
    original_price = models.FloatField(null=False, blank=False)
    selling_price = models.FloatField(null=False, blank=False)
    status = models.BooleanField(default=False, help_text="0=default,1=Hidden")
    trending = models.BooleanField(default=False, help_text="0=default,1=Hidden")
    tag = models.CharField(max_length=150, null=False, blank=False)
    meta_title = models.CharField(max_length=150, null=False, blank=False)
    meta_keyword = models.CharField(max_length=150, null=False, blank=False)
    meta_description = models.TextField(max_length=500, null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.p_name

    class Meta:
        ordering = ['p_name']

    def clean(self):
        super().clean()
        if self.quantity < 10:
            raise ValidationError("Quantity should be at least 10.")

    # Add a constraint at the database level to ensure minimum quantity is 10 what about out of stock 
    def save(self, *args, **kwargs):
        if self.quantity < 10:
            raise ValidationError("Quantity should be at least 10.")
        super().save(*args, **kwargs)
        
class Order(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    fname=models.CharField(max_length=150,null=False)
    lname=models.CharField(max_length=150,null=False)
    email=models.CharField(max_length=150,null=False)
    phone=models.CharField(max_length=150,null=False)
    address=models.TextField(null=False)
    city=models.CharField(max_length=150,null=False)
    state=models.CharField(max_length=150,null=False)
    pincode=models.CharField(max_length=150,null=False)
    total_price=models.FloatField(null=False)
    payment_mode=models.CharField(null=False, max_length=50)
    payment_id= models.CharField(max_length=250, null=True)
    orderstatuses=(
    ('Pending','Pending'),
    ('Out For Shipping','Out For Shipping'),
    ('Completed','Completed'),
    ('Cancelled','Cancelled'),
    ('Refund initialized','Refund initialized'),
    ('Refund successful','Refund successful'),
    )
    status=models.CharField(max_length=150,choices=orderstatuses,default='Pending')
    tracking_no=models.CharField(null=True, max_length=150)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{} - {}'.format(self.id,self.tracking_no)

class ProductReview(models.Model): 
    user = models.ForeignKey(User, on_delete=models.CASCADE) 
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='reviews') 
    rating = models.IntegerField()  # Assuming rating is an integer field for simplicity 
    review = models.TextField() 
    posted_at = models.DateTimeField(auto_now_add=True) 
 
    def __str__(self): 
        return f"Review by {self.user.username} for {self.product.p_name}"
    
class Company(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    phone_number = models.CharField(max_length=20)
    address = models.TextField()
    facebook = models.URLField(blank=True)
    instagram = models.URLField(blank=True)

    def str(self):
        return self.name

class OrderItem(models.Model):
    order=models.ForeignKey(Order,on_delete=models.CASCADE)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    price=models.FloatField(null=False)
    quantity=models.IntegerField(null=False)
    payment_status=models.BooleanField(default=False)
    is_canceled=models.BooleanField(default=False)

    def __str__(self):
         return '{} - {}'.format(self.order.id, self.order.tracking_no)

class Cart(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE, related_name='carts')
    is_paid = models.BooleanField(default=False)
    # session_id = models.CharField(max_length=255, null=True, blank=True) for annonymous 

    def get_cart_total(self):
        cart_items=self.cart_items.all()
        price=[]
        for cart_item in cart_items:
            price.append(cart_item.product.selling_price)
        return sum(price)
    def __str__(self):
        if self.user:
            return f"Cart for {self.user.username}"
        else:
            return f"Anonymous Cart ({self.session_id})"
    
    
class CartItems(models.Model):
    cart = models.ForeignKey(Cart,on_delete=models.CASCADE, related_name='cart_items')
    product=models.ForeignKey(Product,on_delete=models.SET_NULL,null=True,blank=True)
    quantity = models.IntegerField(default=1)
     
    def get_product_price(self):
        price=[self.product.selling_price]
        return sum(price)
    def sub_total(self):
        return self.product.selling_price*self.quantity
    
    def __unicode__(self):
        return self.product
    
    def __str__(self):
        return f"{self.quantity} x {self.product} ---->    {self.cart}"

class cust(models.Model):
    ch=[('Male','Male'),('Female','Female')]
    cust_id=models.ForeignKey(User,on_delete=models.CASCADE)
    state=models.ForeignKey(State,on_delete=models.CASCADE)
    email=models.CharField(max_length=150,null=False) 
    fname=models.CharField(max_length=50,default=None) 
    lname=models.CharField(max_length=50,default=None)  
    phone=models.CharField(max_length=50,default=None)
    gender=models.CharField(max_length=40,choices=ch,default='Male') 
    address=models.TextField(null=False, default='')

templates/all_products.html
{% extends "base.html" %}
{% block content %}
<div class="hero">
  <div class="container">
    <div class="col-lg-5">
      <div class="intro-excerpt">
        <h1>Your Orders</h1>
      </div>
    </div>
    <div class="col-lg-7">
      {% if messages %}
      {% for message in messages %}
      <div class="alert alert-success" role="alert">
        {{ message }}
      </div>
      {% endfor %}
      {% endif %}
    </div>
  </div>
</div>
<div class="untree_co-section before-footer-section">
  <div class="container">
    <div class="row mb-5">
      {% if products %}
      <div class="col-md-12">
        <div class="site-blocks-table">
          <table class="table">
            <thead>
              <tr>
                <th>Order ID</th>
                <th>Sr. No.</th>
                <th>Product Image</th>
                <th>Product Name</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>Total Price</th>
                <th>Payment Status</th>
                <th>Status</th>
                <th>Invoices</th>
              </tr>
            </thead>
            <tbody>
              {% for item in products %}
              <tr>
                <td>{{ item.order.id }}</td>
                <td>{{ forloop.counter }}</td>
                <td class="product-thumbnail">
                  <img src="/media/{{ item.product.p_image }}" alt="Product Image" class="img-fluid">
                </td>
                <td>{{ item.product.p_name }}</td>
                <td>{{ item.price }}</td>
                <td>{{ item.quantity }}</td>
                <td>{{ item.order.total_price }}</td>
                <td>{% if item.payment_status %}Success{% else %}Failed{% endif %}</td> <!-- Display text message for payment status -->
                <td>{{ item.order.status }}</td>
                <td>
                  <a href="{% url 'download_invoice' item.order.id %}" class="btn btn-primary">Download Invoice</a>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
      <div class="col-md-12">
        <a href="{% url 'my_orders' %}" class="btn btn-primary">Back to Orders</a>
      </div>
      {% else %}
      <h2 style="text-align: center;">You have not ordered anything yet, please click here to place an order</h2>
      <div class="col-md-12 m-4" style="text-align: center;">
        <form action="/shop/" method="post">
          {% csrf_token %}
          <button class="btn btn-outline-black col-md-4 btn-sm btn-block">Continue Shopping</button>
        </form>
      </div>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

templates/base.html
{% include "header.html" %}
{%block content%}


{%endblock%}
{% include "footer.html" %}

templates/booking_report.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Booking Report | Om Plastic Mart</title>
    <style>
        body {
            font-family: sans-serif;
            line-height: 1.5;
            color: #111827;
            margin: 0;
            padding: 0;
        }
        header {
            display: flex;
            justify-content: space-between;
            align-items: flex-end;
            padding: 1.25rem 2.5rem;
        }
        hr {
            border: none;
            border-top: 1px solid #e5e7eb;
            margin: 0;
        }
        section {
            padding: 1.25rem 2.5rem;
        }
        table {
            width: 100%;
            border-collapse: collapse;
        }
        th, td {
            padding: 0.75rem 1rem;
            border-bottom: 2px solid #e5e7eb;
        }
        th {
            text-align: left;
            text-transform: uppercase;
            font-weight: bold;
            font-size: 1rem;
            color: black;
            background-color: lightgrey;
            border-bottom: none;
        }
        td {
            font-size: 1rem;
            color: #111827;
        }
        .text-right {
            text-align: right;
        }
        .bg-gray-50 {
            background-color: #ffffff !important;
        }
        .bg-white {
            background-color: #ffffff;
        }
        .font-medium {
            font-weight: 500;
        }
        .text-xs {
            font-size: 1rem;
        }
    </style>
    <title>Booking Report | Om Plastic Mart</title>
</head>
<body>
    <div class="max-w-7xl mx-auto">
        <header>
            <center><h1 style="font-size: 2.25rem; line-height: 1.1;" class="text-gray-900">Order Report</h1></center>
        </header>         

        <hr>

        <section style="display: flex; justify-content: space-between; align-items: flex-start;">
            <div>
                <p class="text-xs">
                    <strong>Company Name:</strong>
                    {{ shop.name }}
                    <br />
                    <strong>Date Generated:</strong>
                    {{ date_generated }}
                </p>
                <p class="text-xs">
                    <strong>Address:</strong><br>
                    {{ shop.address|safe }}
                </p>
                <p class="text-xs">
                    <strong>Contact Details:</strong><br>
                    {{ shop.phone_number }}<br>
                    {{ shop.email }}
                </p>
            </div>
            <div>
                <!-- Add your company logo here -->
                <img src="{% static 'images/c_logo.png' %}" alt="Company Logo" style="max-width: 100px;">                     </div>
            <hr>
        </section>

        <br>
        <br>

        <section style="display: flex; justify-content: space-between;">
            {% comment %} <p class="text-xs">
                <strong>Address:</strong><br>
                {{ shop.address|safe }}
            </p>

            <p class="text-xs text-right">
                <strong>Contact Details:</strong><br>
                {{ shop.contact_number }}<br>
                {{ shop.email }}            
            </p> {% endcomment %}
        </section>

        <section>
            <div>
                {% if records %}
                <table>
                    <thead>
                        <tr>
                            <th>Report Date</th>
                            <th>Customer First Name</th>
                            <th>Customer Last Name</th>
                            <th class="text-right">Phone</th>
                            <th class="text-right">Order Date</th>
                            <th class="text-right">Pin code</th>
                            <th class="text-right">Total amount</th>
                            <th class="text-right">Order Status</th>
                            <th class="text-right">Payment Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for record in records %}
                        <tr>
                            <td>{{ record.created_at|date:"d/m/Y" }}</td>
                            <td>{{ record.fname }}</td>
                            <td>{{ record.lname }}</td>
                            <td>{{ record.phone }}</td>
                            <td>{{ record.created_at|date:"d/m/Y" }}</td>
                            <td>{{ record.pincode }}</td>
                            <td>{{ record.total_price }}</td>
                            <td>{{ record.status }}</td>
                            <td>
                                {% for order_item in record.orderitem_set.all %}
                                {% if order_item.payment_status %}
                                    Paid
                                {% else %}
                                    Not paid
                                {% endif %}
                                {% endfor %}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {% else %}
                <p>No data available for the selected date range.</p>
                {% endif %}
            </div>
        </section>
    </div>
</body>
</html>

templates/change_pass.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <meta name="viewport" content="width=device-width, initial-scale=1.0">  
    <title>Change Password</title>  
    <link href="/static/css/change_pass.css" rel="stylesheet">  
</head>  
<body>  
    <div class="container">  
        <h2>Change Password</h2>  
        <form method="POST" action="{% url 'change_pass' %}">  
        {% csrf_token %}  
            <div class="form-group">  
                <label for="currentpassword">Current Password:</label>  
                <input type="password" id="currentpassword" name="oldpassword" required>  
            </div>  
            <div class="form-group">  
                <label for="newpassword">New Password:</label>  
                <input type="password" id="newpassword" name="newpassword" required>  
            </div>  
            <div class="form-group">  
                <label for="confirm_password">Confirm Password:</label>  
                <input type="password" id="confirm_password" name="confirmpassword" required>  
            </div>  
            <button type="submit">Change Password</button>  
        </form>  
    </div>  
</body>  
</html>

templates/checkout.html
<!-- /*
* Bootstrap 5
* Template Name: Furni
* Template Author: Untree.co
* Template URI: https://untree.co/
* License: https://creativecommons.org/licenses/by/3.0/
*/ -->
{% include "header.html" %}
{% block content %}

<body>
	<!-- Start Hero Section -->
	<div class="hero">
		<div class="container">
			<div class="row justify-content-between">
				<div class="col-lg-5">
					<div class="intro-excerpt">
						<h1>Checkout</h1>
					</div>
				</div>
				<div class="col-lg-7">

				</div>
			</div>
		</div>
	</div>
	<!-- End Hero Section -->

	<div class="untree_co-section">
		<form method="POST" action="{% url 'placeorder' %}">
			{% csrf_token %}
			<div class="container">
				<div class="row mb-5">
					<div class="col-md-12">
						<div class="border p-4 rounded" role="alert">
							Returning customer? <a href="{% url 'login' %}">Click here</a> to login
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-md-6 mb-5 mb-md-0">
						<h2 class="h3 mb-3 text-black">Billing Details</h2>
						<div class="p-3 p-lg-5 border bg-white">
							{% for i in curr_user %}
							<div class="form-group row">
								<div class="col-md-6">
									<label for="c_fname" class="text-black">First Name <span
											class="text-danger">*</span></label>
									<input type="text" value="{{ request.user.first_name }}" class="form-control"
										id="c_fname" name="fname" required>
								</div>
								<div class="col-md-6">
									<label for="c_lname" class="text-black">Last Name <span
											class="text-danger">*</span></label>
									<input type="text" value="{{ request.user.last_name }}" class="form-control"
										id="c_lname" name="lname" required>
								</div>
							</div>

							<div class="form-group row">
								<div class="col-md-12">
									<label for="c_address" class="text-black">Address <span
											class="text-danger">*</span></label>
									<input type="text" value="{{i.address}} " class="form-control" id="c_address"
										name="address" placeholder="Street address" required>
								</div>
							</div>

							<div class="form-group mt-3">
								<label for="c_state_country" class="text-black">City <span
										class="text-danger">*</span></label>
								<input type="text" value=" {{i.city}}" class="form-control" id="c_city" name="city"
									required>
							</div>

							<div class="form-group row">
								<div class="col-md-6">
									<label for="c_state_country" class="text-black">State <span
											class="text-danger">*</span></label>
									<input type="text" value=" {{i.state}}" class="form-control" id="c_state_country"
										name="state" required>
								</div>
								<div class="col-md-6">

									<input type="hidden" value="{{i.payment_mode}} " class="form-control"
										id="c_payment_mode" name="payment_mode" required>
								</div>
								<div class="col-md-6">
									<label for="c_postal_zip" class="text-black">Pincode <span
											class="text-danger">*</span></label>
									<input type="text" value="{{i.pincode}} " class="form-control" id="c_postal_zip"
										name="pincode" required>
								</div>
							</div>

							<div class="form-group row mb-5">
								<div class="col-md-6">
									<label for="c_email_address" class="text-black">Email Address <span
											class="text-danger">*</span></label>
									<input type="text" class="form-control" id="c_email_address" name="email"
										value="{{ request.user.email }}" required>
								</div>
								<div class="col-md-6">
									<label for="c_phone" class="text-black">Phone <span
											class="text-danger">*</span></label>
									<input type="text" value="{{i.phone}} " class="form-control" id="c_phone"
										name="phone" placeholder="Phone Number" required>
								</div>
							</div>

							<div class="form-group">
								<label for="c_order_notes" class="text-black">Order Notes</label>
								<textarea name="c_order_notes" id="c_order_notes" cols="30" rows="5"
									class="form-control" placeholder="Write your notes here..."></textarea>
							</div>
							{% endfor %}
							<br>
							<br>
						</div>
					</div>
					<div class="col-md-6">

						<div class="row mb-5">
							<div class="col-md-12">
								<h2 class="h3 mb-3 text-black">Coupon Code</h2>
								<div class="p-3 p-lg-5 border bg-white">

									<label for="c_code" class="text-black mb-3">Enter your coupon code if you have
										one</label>
									<div class="input-group w-75 couponcode-wrap">
										<input type="text" class="form-control py-3" id="coupon"
											placeholder="Currently Unavailable" readonly>
										<div class="input-group-append">
											&nbsp;&nbsp;&nbsp;<button class="btn btn-black btn-sm" type="button"
												id="button-addon2">Apply</button>
										</div>
									</div>

								</div>
							</div>
						</div>
						<div class="row mb-5">
							<div class="col-md-12">
								<h2 class="h3 mb-3 text-black">Your Order</h2>
								<div class="p-3 p-lg-5 border bg-white">

									<table class="table site-block-order-table mb-5">
										<thead>
											<th>Product</th>
											<th>Total</th>
										</thead>
										<tbody>
											{% for cart_item in cart_items %}
											<tr>
												<td>{{ cart_item.product.p_name }} <strong class="mx-2">x</strong>
													{{ cart_item.quantity }}</td>
												<td>{{ cart_item.sub_total }}</td>
											</tr>
											{% endfor %}
											<tr>
												<td class="text-black font-weight-bold"><strong>Cart Subtotal</strong>
												</td>
												<td class="text-black">{{ total }}</td>
											</tr>
											<tr>
												<td class="text-black font-weight-bold"><strong>Tax (10.0%)</strong>
												</td>
												<td class="text-black">{{ tax }}</td>
											</tr>
											<tr>
												<td class="text-black font-weight-bold"><strong>Order Total</strong>
												</td>
												<td class="text-black font-weight-bold"><strong>
														{{ grand_total}}</strong></td>
											</tr>
										</tbody>
									</table>


									{% comment %} <form action="{% url 'proceed_to_pay' %}" method="POST">
										{% csrf_token %}
										<div class="border p-3 mb-3">
											<h3 class="h6 mb-0">
												<button type="submit" id="payWithRazorpay" name="payWithRazorpay"
													role="button"
													class="btn btn-black btn-lg py-3 btn-block payWithRazorpay ">Pay
													with Razorpay</button>
											</h3>
										</div>
									</form> {% endcomment %}

									{% comment %} <div class="border p-3 mb-5">
										<h3 class="h6 mb-0"><a class="d-block" data-bs-toggle="collapse"
												href="{% url 'thankyou' %}" role="button" aria-expanded="false"
												aria-controls="collapsepaypal">Cash On Delivery</a>
										</h3>
									</div> {% endcomment %}

									<div class="form-group">
										<button type="submit"
											class="btn btn-black btn-lg py-3 btn-block payWithRazorpay">
											Place Order</button>
									</div>

								</div>
							</div>
						</div>
		</form>

		<!-- jQuery library -->
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

		<!-- Other scripts -->
		<script src="/static/css/bootstrap.bundle.min.js"></script>
		<script src="/static/css/tiny-slider.js"></script>
		<script src="/static/css/custom.js"></script>


		<!-- Your custom JavaScript file -->
		<script src="/static/css/checkout.js"></script>
		<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
		<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

</body>

</html>
{% endblock %}

{% block scripts %}
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="/static/css/checkout.js"></script>

{% endblock scripts %}

templates/orders.html
{% extends "base.html" %}
{% block content %}
<div class="hero">
  <div class="container">
    <div class="col-lg-5">
      <div class="intro-excerpt">
        <h1>Your Orders</h1>
      </div>
    </div>
    <div class="col-lg-7">
      {% if messages %}
      {% for message in messages %}
      <div class="alert alert-success" role="alert">
        {{ message }}
      </div>
      {% endfor %}
      {% endif %}
    </div>
  </div>
</div>
<div class="untree_co-section before-footer-section">
  <div class="container">
    <div class="row mb-5">
      {% if orders %}
      <div class="col-md-12">
        <div class="site-blocks-table">
          <table class="table">
            <thead>
              <tr>
                <th>Order ID</th>
                <th>Sr. No.</th>
                <th>Product Image</th>
                <th>Product Name</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>Total Price</th>
                <th>Payment Status</th>
                <th>Status</th>
                <th>Invoices</th>
                <th>Cancel Order</th> <!-- New column for cancel order link -->
              </tr>
            </thead>
            <tbody>
              {% for order in orders %}
              <tr>
                <td rowspan="2">{{ order.id }}</td>
                {% for item in order.orderitem_set.all|slice:":1" %}
                <td>{{ forloop.counter }}</td>
                <td class="product-thumbnail">
                  <img src="/media/{{ item.product.p_image }}" alt="Product Image" class="img-fluid">
                </td>
                <td>{{ item.product.p_name }}</td>
                <td>{{ item.price }}</td>
                <td>{{ item.quantity }}</td>
                <td>{{ order.total_price }}</td>
                <td>{% if item.payment_status %}Success{% else %}Failed{% endif %}</td> <!-- Display text message for payment status -->
                <td>{{ order.status }}</td>
                <td>
                  <a href="{% url 'download_invoice' order.id %}" class="btn btn-primary">Download Invoice</a>
                </td>
                <td>
                  {% if order.status != 'Delivered' %} <!-- Check if the order has been delivered -->
                    <a href="{% url 'cancel_order' order.id %}" class="btn btn-danger">Cancel Order</a>
                  {% endif %}
                </td>
              </tr>
              {% endfor %}
              <tr>
                <td colspan="9">
                  <a href="{% url 'view_all_products' order.id %}">View All Products</a>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
      {% else %}
      <h2 style="text-align: center;">You have not ordered anything yet, please click here to place an order</h2>
      <div class="col-md-12 m-4" style="text-align: center;">
        <form action="/shop/" method="post">
          {% csrf_token %}
          <button class="btn btn-outline-black col-md-4 btn-sm btn-block">Continue Shopping</button>
        </form>
      </div>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}